#! /bin/python3
# -*- coding: Utf-8 -*
##
## EPITECH PROJECT, 2019
## 104intersection_2019
## File description:
## 104intersection
##

import sys

def main(ac, av):
    return (0)

if __name__ == "__main__":
   sys.exit(main(len(sys.argv), sys.argv))

def check_error():
    if (len(argv) != 9):
        exit 84
    elif (argv[1] < 1 or argv[1] > 1):
        exit 84
    for i in range(2, 8):
        try:
            float(argv[i])
        except ValueError:
            exit 84
    if (argv[1] != 3 and argv[8] <= 0):
        exit (84)

#body
check_error()