#! /bin/python3
# -*- coding: Utf-8 -*
##
## EPITECH PROJECT, 2019
## 104intersection_2019
## File description:
## 104intersection
##

import sys

def main(ac, av):
    return (0)

if __name__ == "__main__":
   sys.exit(main(len(sys.argv), sys.argv))